### ISSUE TITLE
Suggestion: use NDI metadata to transfer the depth values

### ISSUE THREAD

**Issue by hybridherbst** [keijiro/NdiQualityTest#1]
Hey keijiro, we used the NDI metadata in the past to store additional data without compression.
There's a whole SDK around that to store data per frame.

The other thing we did / you could try is to unpack the high-res depth data into RGB and send it as additional NDI stream.

**Comment by keijiro** [comment]
It could work, but it may waste lots of bandwidth. I wanted to use NDI to send a volumetric video stream via Wi-Fi. It's not possible to send uncompressed depth frames at 60 fps via Wi-Fi.

Thanks for the suggestion anyway. It could work in some other cases but not in my case.
